---
- hosts: all
  become: true
  tasks:
    - name: stop tomcat
      systemd:
        name: tomcat.service
        state: stopped
    - name: delete old application package
      file:
        path: /usr/local/apache-tomcat-7.0.76/webapps/maven-web-application.war
        state: absent
    - name: copy application package
      copy:
        src: target/maven-web-application.war
        dest: /usr/local/apache-tomcat-7.0.76/webapps/maven-web-application.war
        owner: tomcat
        group: tomcat
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes
    - name: Pause for 1 Minute and continue with play
      pause:
        minutes: 1
    - name: Confirm that 200 OK response is returned
      uri:
        url: "http://{{ ansible_host }}:8080/maven-web-application/"
        status_code: 200    
...
